name: Build Frontend

on:
  push:
    branches:
      - main
      - develop
      
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0'

    - name: Restore dependencies
      run: dotnet restore SpendeeClient/SpendeeClient.csproj

    - name: Build frontend
      run: dotnet build SpendeeClient/SpendeeClient.csproj --configuration Release --no-restore